#!/usr/bin/env node;

var fs, log, pack, path, program, widgets;

pack = require('./package.json');

path = require('path');

widgets = require('./lib/widgets');

program = require('nomnom').colors();

log = require('./lib/logger');

fs = require('fs');

program.command('init').callback(function(options) {
  return widgets.init(options);
}).help('Initializing new widget or theme in the current directory.');

program.command('pack').callback(function(options) {
  return widgets.pack(options);
}).help('Create .zip file in current folder.');

program.command('unpack').callback(function(options) {
  return widgets.unpack(null, options);
}).help('Unpack .zip file in current folder.');

program.command('check').callback(function(options) {
  return widgets.onServerIsExists(options);
}).help('Check if package with that name already exists.');

program.parse();
